service: landfill-permit
provider:
  name: aws
  runtime: python3.8
  apiKeys:
    - apiKey
  stage: dev
  region: us-east-2
  memorySize: 256
  # vpc:
  #   securityGroupIds:
  #     - sg-0902c3c2a4a96394b
  #   subnetIds:
  #     - subnet-32bbd17f
  #     - subnet-de6a9eb6
  #     - subnet-c8664cb3
  environment:
    DB_PATH: 'landfill-permit.cmu6qepwg8ma.us-east-2.rds.amazonaws.com'
    DB_NAME: 'landfill'
    DB_TYPE: 'mysql'
    DB_DRIVER: 'pymysql'
    DB_USER: 'landfill'
    MG_DOMAIN: 'mg.leblibrary.com'


package:
  exclude:
    - .vscode/**
    - node_modules/**
    - .git/**

functions:
  permit:
    handler: handler.issue_permit
    events:
      - http:
          path: create_permit
          method: post
          private: true

plugins:

  - serverless-python-requirements


custom:

  pythonRequirements:

    dockerizePip: false