service: landfill-permit
provider:
  name: aws
  runtime: python3.8
  apiKeys:
    - apiKey
  stage: dev
  region: us-east-2
  profile: lebanonnh.gov
  tags:
    project: solid-waste-permit
    department: DPW
  memorySize: 256
  vpc:
    securityGroupIds:
      - sg-0ba4d0ef536c0d40e
    subnetIds:
      - subnet-0a91d5483073c2489
  environment:
    DB_PATH: 'lebanonnh-solid-waste-facility.cluster-cpmhmrzcfub1.us-east-2.rds.amazonaws.com'
    DB_NAME: 'landfill'
    DB_TYPE: 'mysql'
    DB_DRIVER: 'pymysql'
    DB_USER: 'admin'
    DB_TLS_CERT: 'AmazonRootCA1.pem'
    MG_DOMAIN: 'mg.leblibrary.com'
    DB_PASS: ${ssm:/DB_PASS~true}
    MG_API_KEY: ${ssm:/MG_API_KEY~true}


package:
  exclude:
    - .vscode/**
    - node_modules/**
    - .git/**

functions:
  permit:
    handler: handler.issue_permit
    events:
      - http:
          path: create_permit
          method: post
          private: true

plugins:

  - serverless-python-requirements


custom:

  pythonRequirements:

    dockerizePip: false
